/**:
  ros__parameters:
    test_servo:
      # The model of the servo is Futaba: FP-S148
      # Read the specs for pulse-width and write it accordingly
      pwm_topic: /test_servo/pwm
      scaled_topic: /test_servo/scaled
      channel: 14
      pulse_duration:
        center: 1.44
        min: 0.550
        max: 2.330
      scale:
        center: 0.0
        min: -1.0
        max: 1.0