ros2_pca9685_node:
  ros__parameters:
    frequency: 50.0
    channels:
      channel_0:
        pwm_topic: cybership/servo/channel_0/pwm
        scaled_topic: cybership/servo/channel_0/scaled
        channel: 0
        center: 1.5 #ms
        max: 2.0
        min: 1.0
      channel_1:
        pwm_topic: cybership/servo/channel_1
        channel: 1